image: Visual Studio 2022

install:
  - cinst make
  - cmd: pwd

environment:
  APPVEYOR_RDP_PASSWORD: Keka_121212

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

before_build:
  - dotnet tool restore
  - dotnet restore
  - git submodule update --init z3
  - git submodule update --init runtime

configuration: Release

build:
  project: VSharp.sln

test_script:
  - dotnet test -c Release --logger:Appveyor
