image: Visual Studio 2022

before_build:  
  - dotnet tool restore
  - git submodule update --init CFPQ_GLL
  - dotnet restore
  - git submodule update --init z3
  - git submodule update --init runtime

configuration: Release

build:
  project: VSharp.sln

test_script:
  - dotnet test -c Release --logger:Appveyor
